databases:
  - name: main
    databaseName: main
    user: ror_admin

services:
  - type: web
    name: critiqueall
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: main
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false